config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'restaurants', to: 'restaurants#index'
  get 'restaurants/new', to: 'restaurants#new'
  post 'restaurants', to: 'restaurants#create'
  get 'restaurants/:id', to: 'restaurants#show', as: 'restaurant'
  get 'restaurants/:id/reviews/new', to: 'reviews#new', as: 'reviews'
  post 'restaurants/:id/reviews/new', to: 'reviews#create'

  # resources :restaurants, only: [:index, :show, :new, :create] do
  #   resources :reviews, only: [:create]
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :restaurant, presence: true
  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }
  validates :rating, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurant_path(@restaurant)
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
  end
  def create
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    @review.save
    redirect_to restaurant_path(@restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to 'Main page', restaurants_path, class: 'nav-link' %>
          </li>
        </ul>
        <div>
          <%= link_to 'Add a restaurant', restaurants_new_path, class: 'btn btn-primary' %>
        </div>
      </div>
    </nav>
    <hr>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="container text-center">
  <h1>Restaurants :</h1>
  <% @restaurants.each do |restaurant| %>
    <p><%= link_to restaurant.name, restaurant_path(restaurant) %></p>
  <% end %>

  <%= link_to "+Add a new restaurant", restaurants_new_path, class:"btn btn-primary" %>
</div>

app/views/restaurants/new.html.erb
<div class="container">

  <h1>Hey ! </h1>

  <!-- app/views/restaurants/_form.html.erb -->
  <%= simple_form_for(@restaurant) do |f| %>
    <% if @restaurant.errors.any? %>
      <div class="errors-container">
        <ul>
          <% @restaurant.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <!-- [...] all the fields -->
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category, collection: ["chinese", "italian", "japanese", "french", "belgian"] %>
    <%= f.submit class: 'btn btn-primary'%>
  <% end %>
</div>

app/views/restaurants/show.html.erb
<div class="container text-center">

  <h1><%= @restaurant.name %></h1>

  <p><%= @restaurant.address %></p>

  <p><%= @restaurant.category %></p>

  <hr>
  <h2>Vos avis</h2>
  <hr>
  <div class="review">
    <% @restaurant.reviews.each_with_index do |review, i| %>
    <% if i.even? %>
      <div style="background-color: #F3DE8A">
        <p><%= '⭐' * review.rating %></p>
        <p><%= review.content %></p>
      </div>
    <% else %>
      <div style="background-color: #F1DB4B">
        <p><%= '⭐' * review.rating %></p>
        <p><%= review.content %></p>
      </div>
    <% end %>

    <hr>

    <% end %>
  </div>

  <%= link_to "Leave a review", reviews_path, class:"btn btn-primary" %>

  <%= link_to "Back to main page", restaurants_path, class:"btn btn-primary" %>

</div>

app/views/reviews/new.html.erb
<div class="container">
  <h1>Hi, leave ur review here</h1>
  <%= simple_form_for( [@restaurant, @review]) do |f| %>
    <% if @review.errors.any? %>
      <div class="errors-container">
        <ul>
          <% @review.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <!-- [...] all the fields -->
    <%= f.input :content %>
    <%= f.input :rating, collection: [0,1,2,3,4,5] %>
    <%= f.submit class: 'btn btn-primary'%>
  <% end %>
</div>